version: '2'
services:
  web:
    build: .
    ports:
     - "80:80"
    volumes:
     - .:/var/www/html/
  mysql:
    image: mysql:8.0.33
    environment:
        MYSQL_DATABASE: db
        MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'

